#This Ansible playbook configures an Ubuntu 22.04 host with some useful forensic software and tools that would be useful for analyzing malware.

---
- name: Setup Software on Ubuntu
  hosts: ubuntu_host
  become: yes
  tasks:

    # Update repositories
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install KVM
    - name: Install KVM
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
        state: present

    # Install VirtualBox
    - name: Install VirtualBox
      apt:
        name:
          - virtualbox
        state: present

    # Install Ghidra (using PPA)
    - name: Add Ghidra PPA
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present

    - name: Install Ghidra dependencies
      apt:
        name:
          - openjdk-11-jdk
        state: present

    - name: Download Ghidra
      get_url:
        url: "https://ghidra-sre.org/ghidra_10.0.4_PUBLIC_20210928.zip"
        dest: "/tmp/ghidra.zip"
        mode: '0755'

    - name: Unzip Ghidra
      unarchive:
        src: "/tmp/ghidra.zip"
        dest: "/opt/"
        remote_src: yes

    # Install Metasploit
    - name: Install Metasploit dependencies
      apt:
        name:
          - curl
          - gpg
        state: present

    - name: Add Metasploit GPG key and repo
      apt_key:
        url: "https://apt.metasploit.com/metasploit-framework.gpg.key"
        state: present

    - name: Add Metasploit repository
      apt_repository:
        repo: "deb https://apt.metasploit.com/ lucid main"
        state: present

    - name: Install Metasploit
      apt:
        name:
          - metasploit-framework
        state: present

    # Install an open-source hex editor (wxHexEditor)
    - name: Install wxHexEditor
      apt:
        name:
          - wxhexeditor
        state: present

    # Install Visual Studio Code
    - name: Install Visual Studio Code
      snap:
        name: code
        classic: yes

    # Install portmaster.io firewall (assuming a .deb package is available)
    - name: Download portmaster.io .deb package
      get_url:
        url: "https://URL_TO_PORTMASTER_DEB_PACKAGE"
        dest: "/tmp/portmaster.deb"
        mode: '0755'

    - name: Install portmaster.io
      apt:
        deb: "/tmp/portmaster.deb"

    # Install OBS Studio
    - name: Install OBS Studio
      apt:
        name:
          - obs-studio
        state: present

    # Install Wireshark
    - name: Install Wireshark
      apt:
        name:
          - wireshark
        state: present

    # Configure Wireshark for non-root users
    - name: Add user to wireshark group
      user:
        name: "{{ ansible_user }}"
        groups: wireshark
        append: yes

    - name: Configure Wireshark dumpcap for non-root users
      command: setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/dumpcap
      args:
        warn: no

